### ISSUE TITLE
ScraperWiki: Bankstown City Council, Bankstown, NSW - Broken URL & page changed

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts-parsers#14]
Was https://github.com/openaustralia/planningalerts-parsers/commit/02534ff0ce2ac9554b6172bf5e9f7684ec86a086

A brief look at what is in github suggests this still works, there is just a clickwrap agreement (http://online.bankstown.nsw.gov.au/Planning/Common/Common/Terms.aspx) you are prompted with first.

Code does:

```
  base_url = "http://online.bankstown.nsw.gov.au/Planning/pages/xc.track/SearchApplication.aspx"
  search_url = base_url + "?o=xml&d=#{date_range}&k=LodgementDate&t=#396"
```

and URLs like the below still work.

http://online.bankstown.nsw.gov.au/Planning/pages/xc.track/SearchApplication.aspx?o=html&d=lastmonth&k=LodgementDate&t=%23396&ss=a

**Comment by CloCkWeRX** [comment]
@henare was there something else causing this not to work?

**Comment by CloCkWeRX** [comment]
#16 has the same clickwrap agreement

**Comment by henare** [comment]
@CloCkWeRX I think your investigation looks right.

**Comment by CloCkWeRX** [comment]
https://github.com/planningalerts-scrapers/bankstown/pull/2
