### ISSUE TITLE
ScraperWikiScraper.new("Streamlined Planning through Electronic Applications and Referrals", "SPEAR ,Victoria", "VIC"), # Problematic (gets DAs for lots of councils)

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts-parsers#26]
https://github.com/openaustralia/planningalerts-parsers/commit/02534ff0ce2ac9554b6172bf5e9f7684ec86a086

**Comment by henare** [comment]
For the same reason as you left off The Hills scraper, I'm closing this as it's covered by openaustralia/planningalerts-app#473
