### ISSUE TITLE
 ScraperWikiScraper.new("Victorian Commission for Gambling and Liquor Regulation", "VCGLR", "VIC"), # Problematic (has to search heaps of pages)

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts-parsers#27]
https://github.com/openaustralia/planningalerts-parsers/commit/02534ff0ce2ac9554b6172bf5e9f7684ec86a086

**Comment by henare** [comment]
For the same reason as you left off The Hills scraper, I'm closing this as it's covered by https://github.com/openaustralia/planningalerts-app/issues/473
